apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP # Specification of the service if you need a client's first request
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80
